---

- block:
    # New way of managing keys
    - name: Copy Seafile client apt key
      ansible.builtin.get_url:
        url: '{{ seafile_client_apt_key }}'
        dest:  '{{ seafile_client_apt_key_path }}'
        checksum: '{{ seafile_client_apt_key_checksum }}'
        mode: '0644'
      environment: '{{ seafile_client_download_environment }}'

    - name: Install Seafile client apt repository
      ansible.builtin.apt_repository:
        repo: '{{ seafile_client_apt_repository }}'
        filename: ansible_roles_seafile_client
        state: present
        update_cache: yes
  become: '{{ do_become }}'
  tags: [seafile-client, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
